-- ============================================================
-- Lifestyle Medicine Gateway — Catalog Schema Migration
-- Run this in Supabase Dashboard -> SQL Editor
-- ============================================================

-- Categories (Products, Articles, Recipes)
create table public.categories (
  id int8 primary key generated by default as identity,
  name text not null,
  slug text not null,
  type text not null check (type in ('product', 'article', 'recipe')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.categories enable row level security;
create policy "Categories are viewable by everyone" on public.categories for select using (true);
create policy "Only admins edit categories" on public.categories for all using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

-- Products
create table public.products (
  id int8 primary key generated by default as identity,
  vendor_id uuid references public.vendor_profiles(id) on delete set null,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text,
  price numeric(10,2) not null default 0,
  image_url text,
  stock integer not null default 0,
  status text not null default 'published' check (status in ('draft', 'published', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;
create policy "Products are viewable by everyone" on public.products for select using (true);
create policy "Vendors can insert own products" on public.products for insert with check (auth.uid() = vendor_id);
create policy "Vendors can update own products" on public.products for update using (auth.uid() = vendor_id);
create policy "Vendors can delete own products" on public.products for delete using (auth.uid() = vendor_id);

-- Product <-> Category Joining Table
create table public.product_categories (
  product_id int8 references public.products(id) on delete cascade not null,
  category_id int8 references public.categories(id) on delete cascade not null,
  primary key (product_id, category_id)
);

alter table public.product_categories enable row level security;
create policy "Product categories are viewable by everyone" on public.product_categories for select using (true);
create policy "Vendors can manage their product categories" on public.product_categories for all using (
  exists (select 1 from public.products where id = product_id and vendor_id = auth.uid())
);

-- Articles
create table public.articles (
  id int8 primary key generated by default as identity,
  author_id uuid references public.profiles(id) on delete set null,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.articles enable row level security;
create policy "Articles are viewable by everyone" on public.articles for select using (true);
create policy "Authors can manage their articles" on public.articles for all using (auth.uid() = author_id);

-- Recipes
create table public.recipes (
  id int8 primary key generated by default as identity,
  author_id uuid references public.profiles(id) on delete set null,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text,
  image_url text,
  prep_time integer, -- in minutes
  cook_time integer, -- in minutes
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.recipes enable row level security;
create policy "Recipes are viewable by everyone" on public.recipes for select using (true);
create policy "Authors can manage their recipes" on public.recipes for all using (auth.uid() = author_id);

-- Helper Triggers
create trigger update_categories_updated_at before update on public.categories for each row execute function public.update_updated_at();
create trigger update_products_updated_at before update on public.products for each row execute function public.update_updated_at();
create trigger update_articles_updated_at before update on public.articles for each row execute function public.update_updated_at();
create trigger update_recipes_updated_at before update on public.recipes for each row execute function public.update_updated_at();
