/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudiesRouteImport } from './routes/studies'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NaturalRemediesRouteImport } from './routes/natural-remedies'
import { Route as MemesRouteImport } from './routes/memes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as VendorsSlugRouteImport } from './routes/vendors.$slug'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiesRoute = StudiesRouteImport.update({
  id: '/studies',
  path: '/studies',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NaturalRemediesRoute = NaturalRemediesRouteImport.update({
  id: '/natural-remedies',
  path: '/natural-remedies',
  getParentRoute: () => rootRouteImport,
} as any)
const MemesRoute = MemesRouteImport.update({
  id: '/memes',
  path: '/memes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsSlugRoute = VendorsSlugRouteImport.update({
  id: '/vendors/$slug',
  path: '/vendors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/charts': typeof ChartsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/memes': typeof MemesRoute
  '/natural-remedies': typeof NaturalRemediesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/studies': typeof StudiesRoute
  '/terms': typeof TermsRoute
  '/vendor': typeof VendorRoute
  '/videos': typeof VideosRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/charts': typeof ChartsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/memes': typeof MemesRoute
  '/natural-remedies': typeof NaturalRemediesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/studies': typeof StudiesRoute
  '/terms': typeof TermsRoute
  '/vendor': typeof VendorRoute
  '/videos': typeof VideosRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/vendors': typeof VendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/charts': typeof ChartsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/memes': typeof MemesRoute
  '/natural-remedies': typeof NaturalRemediesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/studies': typeof StudiesRoute
  '/terms': typeof TermsRoute
  '/vendor': typeof VendorRoute
  '/videos': typeof VideosRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/charts'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/login'
    | '/memes'
    | '/natural-remedies'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/search'
    | '/signup'
    | '/studies'
    | '/terms'
    | '/vendor'
    | '/videos'
    | '/articles/$slug'
    | '/products/$slug'
    | '/recipes/$slug'
    | '/vendors/$slug'
    | '/articles/'
    | '/products/'
    | '/recipes/'
    | '/vendors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/charts'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/login'
    | '/memes'
    | '/natural-remedies'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/search'
    | '/signup'
    | '/studies'
    | '/terms'
    | '/vendor'
    | '/videos'
    | '/articles/$slug'
    | '/products/$slug'
    | '/recipes/$slug'
    | '/vendors/$slug'
    | '/articles'
    | '/products'
    | '/recipes'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/charts'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/login'
    | '/memes'
    | '/natural-remedies'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/search'
    | '/signup'
    | '/studies'
    | '/terms'
    | '/vendor'
    | '/videos'
    | '/articles/$slug'
    | '/products/$slug'
    | '/recipes/$slug'
    | '/vendors/$slug'
    | '/articles/'
    | '/products/'
    | '/recipes/'
    | '/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ChartsRoute: typeof ChartsRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  MemesRoute: typeof MemesRoute
  NaturalRemediesRoute: typeof NaturalRemediesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  StudiesRoute: typeof StudiesRoute
  TermsRoute: typeof TermsRoute
  VendorRoute: typeof VendorRoute
  VideosRoute: typeof VideosRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  VendorsSlugRoute: typeof VendorsSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studies': {
      id: '/studies'
      path: '/studies'
      fullPath: '/studies'
      preLoaderRoute: typeof StudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natural-remedies': {
      id: '/natural-remedies'
      path: '/natural-remedies'
      fullPath: '/natural-remedies'
      preLoaderRoute: typeof NaturalRemediesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memes': {
      id: '/memes'
      path: '/memes'
      fullPath: '/memes'
      preLoaderRoute: typeof MemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$slug': {
      id: '/vendors/$slug'
      path: '/vendors/$slug'
      fullPath: '/vendors/$slug'
      preLoaderRoute: typeof VendorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ChartsRoute: ChartsRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  MemesRoute: MemesRoute,
  NaturalRemediesRoute: NaturalRemediesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  StudiesRoute: StudiesRoute,
  TermsRoute: TermsRoute,
  VendorRoute: VendorRoute,
  VideosRoute: VideosRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  VendorsSlugRoute: VendorsSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
